alter session set NLS_LANGUAGE = AMERICAN;

create table users
(
    id       number(10) generated by default as identity primary key,
    login    varchar2(20)           not null unique,
    password varchar2(200)          not null,
    name     nvarchar2(40)          not null,
    email    varchar2(40)           null,
    phone    varchar2(15)           null,
    blocked  number(1, 0) default 0 not null,
    role_id  number(10)             not null,
    order_id number(10)             null
);

create table roles
(
    id   number(10) generated by default as identity primary key,
    name nvarchar2(30) not null unique
);

create table addresses
(
    id        number(10) generated by default as identity primary key,
    country   nvarchar2(30) not null,
    locality  nvarchar2(40) not null,
    street    nvarchar2(40) null,
    house     nvarchar2(10) not null,
    apartment nvarchar2(10) null,
    user_id   number(10)    not null
);

create table dishes
(
    id          number(10) generated by default as identity primary key,
    name        nvarchar2(40)             not null,
    description nvarchar2(200)            not null,
    image_url   varchar2(100)             null,
    weight      number(5)     default (0) not null check (weight >= 0),
    price       binary_double default (0) not null check (price >= 0),
    discount    number(3)     default (0) not null check (discount >= 0 and discount <= 100),
    category_id number(10)                not null
);

create table categories
(
    id   number(10) generated by default as identity primary key,
    name nvarchar2(30) not null unique
);

create table orders
(
    id             number(10) generated by default as identity primary key,
    price          binary_double default (0) null check (price >= 0),
    specified_date timestamp(0)              null,
    order_date     timestamp(0)              null,
    delivery_date  timestamp(0)              null,
    address_id     number(10)                null,
    status_id      number(10)                not null,
    customer_id    number(10)                not null,
    manager_id     number(10)                null
);

create table statuses
(
    id   number(10) generated by default as identity primary key,
    name nvarchar2(30) not null unique
);

create table order_items
(
    id       number(10) generated by default as identity primary key,
    quantity number(10) default (0) not null check (quantity >= 0),
    dish_id  number(10)             not null,
    order_id number(10)             not null
);

create table reviews
(
    id        number(10) generated by default as identity primary key,
    grade     number(3)      null check (grade >= 1 and grade <= 5),
    "comment" nvarchar2(200) null,
    "date"    timestamp(0)   not null,
    user_id   number(10)     not null
);

alter table users
    add
        constraint user_role_fk foreign key (role_id) references roles (id);
alter table users
    add
        constraint user_order_fk foreign key (order_id) references orders (id);

alter table addresses
    add
        constraint address_user_fk foreign key (user_id) references users (id);

alter table dishes
    add
        constraint dish_category_fk foreign key (category_id) references categories (id);

alter table orders
    add
        constraint order_address_fk foreign key (address_id) references addresses (id);
alter table orders
    add
        constraint order_status_fk foreign key (status_id) references statuses (id);
alter table orders
    add
        constraint order_customer_fk foreign key (customer_id) references users (id);
alter table orders
    add
        constraint order_manager_fk foreign key (manager_id) references users (id);

alter table order_items
    add
        constraint order_item_dish_fk foreign key (dish_id) references dishes (id);
alter table order_items
    add
        constraint order_item_order_fk foreign key (order_id) references orders (id);

alter table reviews
    add
        constraint review_user_fk foreign key (user_id) references users (id);

create view order_items_dishes_view
as
select o.order_id, d.price, d.discount, o.quantity
from order_items o
         join dishes d on o.dish_id = d.id;

-- alter table users drop constraint user_role_fk;
-- alter table users drop constraint user_order_fk;
-- alter table addresses drop constraint address_user_fk;
-- alter table dishes drop constraint dish_category_fk;
-- alter table orders drop constraint order_address_fk;
-- alter table orders drop constraint order_status_fk;
-- alter table orders drop constraint order_customer_fk;
-- alter table orders drop constraint order_manager_fk;
-- alter table order_items drop constraint order_item_dish_fk;
-- alter table order_items drop constraint order_item_order_fk;
-- alter table reviews drop constraint review_user_fk;
--
-- drop table users;
-- drop table roles;
-- drop table addresses;
-- drop table dishes;
-- drop table categories;
-- drop table orders;
-- drop table statuses;
-- drop table order_items;
-- drop table reviews;
--
-- drop view order_items_dishes_view;
